# Generated by Django 5.1.2 on 2024-11-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_menucategory_menu_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='menuapp.menucategory'),
        ),
    ]
