# Generated by Django 5.1.2 on 2024-11-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Person_Name',
        ),
    ]
