# Generated by Django 5.1.2 on 2024-11-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_person_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('guest_count', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
