# Generated by Django 5.1.2 on 2024-11-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'permissions': [('can_change_category', 'Can change category')]},
        ),
    ]
